# Generated by Django 3.2.13 on 2022-06-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineApp', '0002_auto_20220627_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDFSave', models.FileField(null=True, upload_to='SECU-PDF/', verbose_name='')),
            ],
        ),
    ]
