# Generated by Django 3.2.13 on 2022-06-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineApp', '0004_alter_pdfs_pdfsave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfs',
            name='PDFSave',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
